---
version: "3.7"
services:
#  traefik as a service
  api:
    image: backend-v1
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`edu.exitoied.com.br`)
      - traefik.http.services.api.loadbalancer.server.port=4000
      - traefik.http.routers.api.entrypoints=api
      - traefik.http.routers.api.tls.certresolver=letsencryptresolver
    environment:
      - ENVIRONMENT=PROD
      - DB_USER=remote
      - DB_PASS=R3m0t3_devDB@2024
      - DB_HOST=172.40.37.99
      - DB_PORT=3306
      - DB_HOST_LOCAL=172.40.37.99
      - DATABASE=college
      - REDIS_HOST=redis
      - REDIS_PORT=7000     
      - REDIS_PASS=M3g4_devRD@2021
      - APP_SECRET=megapbx_jwt_flux
      - TZ=America/Sao_Paulo 
    volumes:
      - "/opt/app/files:/usr/src/app/public"
    ports:
      - 4000:4000
    networks:
      - exitoied

  frontend:
    image: frontend-v1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`edu.exitoied.com.br`)
        - traefik.http.services.frontend.loadbalancer.server.port=80
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.routers.frontend.tls.certresolver=letsencryptresolver
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - exitoied
  redis:
    image: bitnami/redis:7.0
    environment:
      - REDIS_PORT_NUMBER=7000
      - REDIS_PASSWORD=M3g4_devRD@2021    
    ports:
      - '7000:7000'
    networks:
      - exitoied  
networks:
  exitoied:
    external: true
...

